name: rishovsblog
favicon: null
layout_spectrum: 0.019359849859029055
typography_spectrum: 0.09335675649344921
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.16482412815093994
  lightness: 0.5532395232003182
  saturation: 0.9249537556897849
  rhythmicContrast: 0.856758528156206
purpose: []
